### ISSUE TITLE
[Windows] error: The cache directory couldn't be determined 

### ISSUE THREAD

**Issue by lost22git** [inko-lang/ivm#2]
### Please describe the bug

as title

### Please list the exact steps necessary to reproduce the bug

ivm \<any subcommand\>

### Operating system

Windows

### ivm version

0.5.0

### Rust version

rustc 1.78.0-nightly

**Comment by yorickpeterse** [comment]
@lost22git Inko and ivm don't support Windows at this time, though it seems I forgot to update the ivm README when Windows support was removed, so I'll fix that. For Windows your best option is to use WSL.
